name: Flutter Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:   # امکان اجرای دستی از تب Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # اگر نسخه خاصی می‌خوای:
          # flutter-version: '3.24.5'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # - name: Analyze code
      #   run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK (Release)
        run: flutter build apk --release

      # اگر AAB می‌خوای (برای گوگل‌پلی):
      # - name: Build App Bundle
      #   run: flutter build appbundle --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7